services:
  fileshelter:
    image: epoupon/fileshelter:latest
    container_name: fileshelter
    volumes:
      - ${CONFIG_PATH}:/var/fileshelter
      - ./fileshelter.conf:/etc/fileshelter.conf
    user: 1000:1000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=5091"
      - "traefik.http.routers.${SUBDOMAIN}.middlewares=tinyauth"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
