services:
  caddy:
    build: .
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      # The NET_ADMIN capability allows it to override the low default limits
      # of the operating system without having to change kernel parameters via sysctl
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-network
volumes:
  caddy_data:
  caddy_config:

networks:
  caddy-network:
    driver: bridge
