services:
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    network_mode: host
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - /mnt/plexiglass:/data
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb

volumes:
  plex_config:
  plex_transcode:
