services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - ${CONFIG_PATH}/filebrowser.db:/database.db
      - ./settings.json:/.filebrowser.json
      - ${MEDIA_SHARE}:/srv
    user: 1000:1000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=80"
      - "traefik.http.routers.${SUBDOMAIN}.middlewares=oidc-auth"
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
