services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ND_BASEURL: https://${SUBDOMAIN}.bowline.im
    volumes:
      - ${BASE_PATH}/navidrome/data:/data
      - ${MEDIA_SHARE}/media/music:/music:ro
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=4533"

  soulmate:
    image: banankungen/soulmate
    container_name: soulmate
    env_file:
      - .env
      - .env.soulmate
    volumes:
      - ${BASE_PATH}/soulmate:/config
      - ${MEDIA_SHARE}:/share
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SOULMATE_SUBDOMAIN}.rule=Host(`${SOULMATE_SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SOULMATE_SUBDOMAIN}.loadbalancer.server.port=7373"
      - "traefik.http.routers.${SOULMATE_SUBDOMAIN}.middlewares=tinyauth"

networks:
  frontend:
    external: true
  backend:
    external: true
