services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4444:3000/tcp"
      - "9001:80/tcp"
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - adguard_net

networks:
  adguard_net:
    driver: bridge

volumes:
  adguard_work:
  adguard_conf:
