services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    expose:
      - 3000
      - 80
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - caddy_network
      - adguard_net
    labels:
      caddy: adguard.bowline.im
      caddy.@local: "remote_ip private_ranges"
      caddy.route: "@local"
      caddy.route.reverse_proxy: "{{upstreams 80}}"
      caddy.tls.protocols: tls1.3

volumes:
  adguard_work:
  adguard_conf:

networks:
  caddy_network:
    external: true
  adguard_net:
