services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4444:80" # Or use :3000 for first time setup
    volumes:
      - ${CONFIG_PATH}/work:/opt/adguardhome/work
      - ${CONFIG_PATH}/conf:/opt/adguardhome/conf
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      # Or puse port 3000 for first time setup
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
  backend:
    external: true
