services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    env_file:
      - ./.env
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/plexiglass:/media # Using same media location
    devices:
      - /dev/dri:/dev/dri # For Intel/AMD GPU transcoding
      - /dev/bus/usb:/dev/bus/usb
    networks:
      - frontend
      - jellyfin_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.bowline.im`)"
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=8096"

volumes:
  jellyfin_config:
  jellyfin_cache:

networks:
  frontend:
    external: true
  jellyfin_net:
