services:
  bowlinedandy:
    container_name: bowlinedandy
    env_file:
      - ./.env
    environment:
      - TZ=${TZ}
    image: boredazfcuk/icloudpd:latest
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_PATH}:/home/${user}/iCloud

  susifluna:
    container_name: susifluna
    env_file:
      - ./.env.ignore.susy
    environment:
      - TZ=${TZ}
    image: boredazfcuk/icloudpd:latest
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_PATH}:/home/${user}/iCloud
